# Название нашего CI/CD пайплайна
name: CI Pipeline

# Указываем когда запускать pipeline:
# - при каждом push в ветки main, development, release
# - при создании Pull Request в ветку main
on:
  push:
    branches: [ main, development, release ]
  pull_request:
    branches: [ main ]

# Задания которые будут выполняться
jobs:
  build-and-test:
    # Используем последнюю версию Ubuntu как среду выполнения
    runs-on: ubuntu-latest
    
    steps:
      # Шаг 1: Скачиваем код репозитория
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Шаг 2: Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
     # Шаг 3: Проверяем что файлы проекта существуют
      - name: Check project files
        run: |
          echo "Checking project files..."
          test -f file1.txt && echo "file1.txt - PASSED" || echo "file1.txt - not found"
          test -f file2.txt && echo "file2.txt - PASSED" || echo "file2.txt - not found"
          test -f file3.txt && echo "file3.txt - PASSED" || echo "file3.txt - not found"
          test -f game.py && echo "game.py - PASSED" || echo "game.py - not found"
          echo "File check completed!"
